---
title: "Réseau de publications scientifiques"
output:
  html_document:
    df_print: paged
---


```{r,include=FALSE}
library(mongolite)
library(ggplot2)
library(dplyr)
library(visNetwork)
```



```{r,include=FALSE}
#1 - CONNECTION

mdb = mongo(collection="hal_irisa_2021", db="publications",
           url="mongodb+srv://etudiant:ur2@clusterm1.0rm7t.mongodb.net/",
           verbose=TRUE)

```



```{r,include=FALSE}
#2-Requête
#Récupération des 20 auteurs les plus prolifiques

q1='[
    {"$unwind" : "$authors"}, 
    {"$group" : {"_id" : {"Name":"$authors.name","First_name":"$authors.firstname"}, "number" : { "$sum" : 1 } }}, 
    {"$sort" : {"number" : -1}},
    {"$limit": 20}
]'
df1 <- mdb$aggregate(pipeline=q1)

df1$name <- df1$'_id'$Name
df1$firstname <- df1$'_id'$First_name
df1 <- df1 %>% select(name, firstname, number)


#Récupération de la liste des publications de chacun des auteurs

#Initialisation du data frame
df = data.frame(matrix(vector(), 0, 3, dimnames=list(c(), c("nom","prenom","titres"))),stringsAsFactors=F)

#Pour chaque auteur on récupère ses publications qu'on stock dans le data frame
for (i in 1:nrow(df1)){
  n <- as.character(df1[i,1])
  p <- as.character(df1[i,2])
  query=paste('{"authors":{"$elemMatch":{"name":"',n,'", "firstname":"',p,'"}}}',sep="")
  titres <- mdb$find(query = query ,fields = '{"title":true}') %>% select(title)
  t <- list(titres)
  df <- rbind(df, data_frame(nom=n,prenom=p, titres=t)) 
}
```





```{r,include=FALSE}
#3 - Calcul locaux

#Calcul des liens entre auteurs

#Vecteurs qui contiennent pour chaque connexion (publication commune) les noeuds correspondants
link_from <- c()
link_to <- c()

#Vecteur qui contient l'intensité de la connexion (nb de publications en commun)
width <- c()

for (i in 1:20){  #Pour chaque auteur
  for (j in 1:20){ #On compare à chaque auteur
    if (i<j){ #Pour ne pas avoir le lien d'un auteur avec lui même ou 2 liens déja connus
       a <- df[[3]][[i]]$title   #Publication de l'auteur i
       b <- df[[3]][[j]]$title    #Publication de l'auteur j
       sim <- length(intersect(a,b)) #Donne le nombre de publication en commun entre i et j
       if (sim >0){    #Si il y a au moins une publication en commun, on stocke les infos voulus
         link_from <- c(link_from,i)
         link_to <- c(link_to,j)
         width <- c(width,sim)
       }
    }
  }
}

#Création d'une variable groupe qui discrimine par le nombre de publication
group <- function(ligne){
  if(ligne[3]>=15){
    return("Plus de 15 \n publications ")
  }
  else if(ligne[3]>=10){
    return("Entre 10 et \n 14 publications ")
  }
  else{
    return("Moins de 10 \n publications")
  }
}
df1$group <- as.factor(apply(df1,MARGIN = 1,group))


 
```






```{r,echo=FALSE}
#4-Visualisation

#Création du réseau de publications
nodes <-data_frame(id=1:20,
                   label=df1[,1],
                   group=df1[,4],
                   title = paste0("<p> Publications de ",df1[,2]," ",df1[,1]," : ", df1[,3]," </p>"))

edges <- data.frame(from=link_from,
                    to =link_to,
                    value=width,
                    title = paste0(df1[link_from,1]," et \n",df1[link_to,1]," ont ",width," publication(s) commune(s)."))

visNetwork(nodes, edges,
           main = "Réseau de publications scientifiques",
           submain = "Passez sur les noeuds ou les arrêtes pour obtenir les informations correspondantes") %>% 
  visLegend(width = 0.1, position = "left", main = "Groupe de \n scientifiques") %>%
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE,selectedBy = "group") %>%
  visInteraction(hover=TRUE,hoverConnectedEdges=TRUE)
  
```




